version: "3"

services:

  ckan:
    build:
      context: ckan/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    env_file:
      - env/prod.env
    links:
      - db
      - solr
      - redis
    ports:
      - "127.0.0.1:${CKAN_PORT}:5000"
    volumes:
      - ckan_storage:/var/lib/ckan
    networks:
      - datalake-net
    restart: unless-stopped

  db:
    build:
      context: postgresql/
      args:
        - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ckan"]
    ports:
      - 127.0.0.1:${DB_EXPOSE_PORT}:5432/tcp
    networks:
      - datalake-net
    restart: unless-stopped

  solr:
    build:
      context: solr/
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index
    networks:
      - datalake-net
    restart: unless-stopped

  redis:
    image: redis:alpine
    networks:
      - datalake-net
    restart: unless-stopped
    
volumes:
  ckan_storage:
  pg_data:
  solr_data:

networks:
  datalake-net:
