version: "3"

services:

  ckan:
    build:
      dockerfile: Dockerfile.dev
    env_file:
      - env/dev.env

  db:
    environment:
      - PGDATA=/var/lib/postgresql/data/db_dev
    volumes:
      - pg_data:/var/lib/postgresql/data_dev


